// Auto-generated by LibreLane
module soc_top(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input rst,
  input clk,
  input instruct_en0,
  input instruct_en1,
  output[31:0] result0,
  output[31:0] result1
);
endmodule
