DESIGN_NAME: dual_core_soc
VERILOG_FILES: dir::src/*.v
VERILOG_POWER_DEFINE: USE_POWER_PINS
PDK: sky130A
CLOCK_PORT: clk
CLOCK_PERIOD: 20.0
SYNTH_STRATEGY: "DELAY 0"
PNR_SDC_FILE: dir::src/impl.sdc
SIGNOFF_SDC_FILE: dir::src/signoff.sdc
VDD_NETS: [VPWR]
GND_NETS: [VGND]
IO_DELAY_CONSTRAINT: 20
CLOCK_UNCERTAINTY_CONSTRAINT: 0.25
CLOCK_TRANSITION_CONSTRAINT: 0.15
TIME_DERATING_CONSTRAINT: 5
OUTPUT_CAP_LOAD: 33.442
MAX_TRANSITION_CONSTRAINT: 0.75
MAX_FANOUT_CONSTRAINT: 32
MAX_CAPACITANCE_CONSTRAINT: 0.2
FP_SIZING: absolute
DIE_AREA: [0, 0, 1000, 1000]
CORE_AREA: [30, 30, 970, 970]
FP_CORE_UTIL: 40
FP_PDN_CORE_RING: true
FP_PDN_ENABLE_RAILS: true
FP_PDN_HORIZONTAL_LAYER: met5
FP_PDN_VERTICAL_LAYER: met4
PDN_VWIDTH: 3.1
PDN_HWIDTH: 3.1
PDN_VPITCH: 90
PDN_HPITCH: 90
PDN_VOFFSET: 10
PDN_HOFFSET: 10
PDN_SKIPTRIM: true
PDN_CORE_RING_VWIDTH: 3.1
PDN_CORE_RING_HWIDTH: 3.1
PDN_CORE_RING_VSPACING: 1.7
PDN_CORE_RING_HSPACING: 1.7
PDN_CORE_RING_VOFFSET: 8
PDN_CORE_RING_HOFFSET: 8
PL_TARGET_DENSITY: 0.50
PL_TIMING_DRIVEN: true
PL_RESIZER_TIMING_OPTIMIZATIONS: true
PL_RESIZER_DESIGN_OPTIMIZATIONS: true
PL_RESIZER_BUFFER_INPUT_PORTS: true
PL_RESIZER_MAX_SLEW_MARGIN: 10
PL_RESIZER_MAX_CAP_MARGIN: 10
PL_RESIZER_SETUP_REPAIR_TNS_PCT: 25
PL_RESIZER_SETUP_MAX_BUFFER_PCT: 10
PL_RESIZER_ALLOW_SETUP_VIOS: true
GPL_CELL_PADDING: 2
DPL_CELL_PADDING: 2
CTS_CLK_BUFFERS:
  - sky130_fd_sc_hd__clkbuf_1
  - sky130_fd_sc_hd__clkbuf_2
  - sky130_fd_sc_hd__clkbuf_4
  - sky130_fd_sc_hd__clkbuf_8
CTS_ROOT_BUFFER: sky130_fd_sc_hd__clkbuf_8
CTS_SINK_CLUSTERING_ENABLE: true
CTS_SINK_CLUSTERING_SIZE: 16
CTS_SINK_CLUSTERING_MAX_DIAMETER: 50
RUN_POST_GRT_RESIZER_TIMING: true
IO_PIN_ORDER_CFG: dir::pin_order.cfg
pdk::sky130*:
  CLOCK_PERIOD: 20.0
