// Auto-generated by LibreLane
module soc_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  output uart_tx,
  output[7:0] led,
  output mbox_c0_to_c1_flag,
  output mbox_c1_to_c0_flag
);
endmodule
