// Auto-generated by LibreLane
module riscv_soc_top(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input rst_n,
  output uart_tx,
  input uart_rx,
  output[7:0] led
);
endmodule
