/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module riscv_soc_top(clk, rst_n, uart_rx, uart_tx, gpio_in, gpio_out, axi_awaddr, axi_awvalid, axi_awready, axi_wdata, axi_wstrb, axi_wvalid, axi_wready, axi_bresp, axi_bvalid, axi_bready, axi_araddr, axi_arvalid, axi_arready, axi_rdata, axi_rresp
, axi_rvalid, axi_rready, ext_interrupt);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input uart_rx;
  wire uart_rx;
  output uart_tx;
  wire uart_tx;
  input [7:0] gpio_in;
  wire [7:0] gpio_in;
  output [7:0] gpio_out;
  wire [7:0] gpio_out;
  input [31:0] axi_awaddr;
  wire [31:0] axi_awaddr;
  input axi_awvalid;
  wire axi_awvalid;
  output axi_awready;
  wire axi_awready;
  input [31:0] axi_wdata;
  wire [31:0] axi_wdata;
  input [3:0] axi_wstrb;
  wire [3:0] axi_wstrb;
  input axi_wvalid;
  wire axi_wvalid;
  output axi_wready;
  wire axi_wready;
  output [1:0] axi_bresp;
  wire [1:0] axi_bresp;
  output axi_bvalid;
  wire axi_bvalid;
  input axi_bready;
  wire axi_bready;
  input [31:0] axi_araddr;
  wire [31:0] axi_araddr;
  input axi_arvalid;
  wire axi_arvalid;
  output axi_arready;
  wire axi_arready;
  output [31:0] axi_rdata;
  wire [31:0] axi_rdata;
  output [1:0] axi_rresp;
  wire [1:0] axi_rresp;
  output axi_rvalid;
  wire axi_rvalid;
  input axi_rready;
  wire axi_rready;
  input ext_interrupt;
  wire ext_interrupt;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire \counter[0] ;
  wire \counter[10] ;
  wire \counter[11] ;
  wire \counter[12] ;
  wire \counter[13] ;
  wire \counter[14] ;
  wire \counter[15] ;
  wire \counter[16] ;
  wire \counter[17] ;
  wire \counter[18] ;
  wire \counter[19] ;
  wire \counter[1] ;
  wire \counter[20] ;
  wire \counter[21] ;
  wire \counter[22] ;
  wire \counter[23] ;
  wire \counter[24] ;
  wire \counter[25] ;
  wire \counter[26] ;
  wire \counter[27] ;
  wire \counter[28] ;
  wire \counter[29] ;
  wire \counter[2] ;
  wire \counter[30] ;
  wire \counter[31] ;
  wire \counter[3] ;
  wire \counter[4] ;
  wire \counter[5] ;
  wire \counter[6] ;
  wire \counter[7] ;
  wire \counter[8] ;
  wire \counter[9] ;
  sky130_fd_sc_hd__inv_2 _077_ (
    .A(\counter[0] ),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xor2_2 _078_ (
    .A(\counter[0] ),
    .B(axi_araddr[0]),
    .X(axi_rdata[0])
  );
  sky130_fd_sc_hd__xor2_2 _079_ (
    .A(\counter[1] ),
    .B(axi_araddr[1]),
    .X(axi_rdata[1])
  );
  sky130_fd_sc_hd__xor2_2 _080_ (
    .A(\counter[2] ),
    .B(axi_araddr[2]),
    .X(axi_rdata[2])
  );
  sky130_fd_sc_hd__xor2_2 _081_ (
    .A(\counter[3] ),
    .B(axi_araddr[3]),
    .X(axi_rdata[3])
  );
  sky130_fd_sc_hd__xor2_2 _082_ (
    .A(\counter[4] ),
    .B(axi_araddr[4]),
    .X(axi_rdata[4])
  );
  sky130_fd_sc_hd__xor2_2 _083_ (
    .A(\counter[5] ),
    .B(axi_araddr[5]),
    .X(axi_rdata[5])
  );
  sky130_fd_sc_hd__xor2_2 _084_ (
    .A(\counter[6] ),
    .B(axi_araddr[6]),
    .X(axi_rdata[6])
  );
  sky130_fd_sc_hd__xor2_2 _085_ (
    .A(\counter[7] ),
    .B(axi_araddr[7]),
    .X(axi_rdata[7])
  );
  sky130_fd_sc_hd__xor2_2 _086_ (
    .A(\counter[8] ),
    .B(axi_araddr[8]),
    .X(axi_rdata[8])
  );
  sky130_fd_sc_hd__xor2_2 _087_ (
    .A(\counter[9] ),
    .B(axi_araddr[9]),
    .X(axi_rdata[9])
  );
  sky130_fd_sc_hd__xor2_2 _088_ (
    .A(\counter[10] ),
    .B(axi_araddr[10]),
    .X(axi_rdata[10])
  );
  sky130_fd_sc_hd__xor2_2 _089_ (
    .A(\counter[11] ),
    .B(axi_araddr[11]),
    .X(axi_rdata[11])
  );
  sky130_fd_sc_hd__xor2_2 _090_ (
    .A(\counter[12] ),
    .B(axi_araddr[12]),
    .X(axi_rdata[12])
  );
  sky130_fd_sc_hd__xor2_2 _091_ (
    .A(\counter[13] ),
    .B(axi_araddr[13]),
    .X(axi_rdata[13])
  );
  sky130_fd_sc_hd__xor2_2 _092_ (
    .A(\counter[14] ),
    .B(axi_araddr[14]),
    .X(axi_rdata[14])
  );
  sky130_fd_sc_hd__xor2_2 _093_ (
    .A(\counter[15] ),
    .B(axi_araddr[15]),
    .X(axi_rdata[15])
  );
  sky130_fd_sc_hd__xor2_2 _094_ (
    .A(\counter[16] ),
    .B(axi_araddr[16]),
    .X(axi_rdata[16])
  );
  sky130_fd_sc_hd__xor2_2 _095_ (
    .A(\counter[17] ),
    .B(axi_araddr[17]),
    .X(axi_rdata[17])
  );
  sky130_fd_sc_hd__xor2_2 _096_ (
    .A(\counter[18] ),
    .B(axi_araddr[18]),
    .X(axi_rdata[18])
  );
  sky130_fd_sc_hd__xor2_2 _097_ (
    .A(\counter[19] ),
    .B(axi_araddr[19]),
    .X(axi_rdata[19])
  );
  sky130_fd_sc_hd__xor2_2 _098_ (
    .A(\counter[20] ),
    .B(axi_araddr[20]),
    .X(axi_rdata[20])
  );
  sky130_fd_sc_hd__xor2_2 _099_ (
    .A(\counter[21] ),
    .B(axi_araddr[21]),
    .X(axi_rdata[21])
  );
  sky130_fd_sc_hd__xor2_2 _100_ (
    .A(\counter[22] ),
    .B(axi_araddr[22]),
    .X(axi_rdata[22])
  );
  sky130_fd_sc_hd__xor2_2 _101_ (
    .A(\counter[23] ),
    .B(axi_araddr[23]),
    .X(axi_rdata[23])
  );
  sky130_fd_sc_hd__xor2_2 _102_ (
    .A(\counter[24] ),
    .B(axi_araddr[24]),
    .X(axi_rdata[24])
  );
  sky130_fd_sc_hd__xor2_2 _103_ (
    .A(\counter[25] ),
    .B(axi_araddr[25]),
    .X(axi_rdata[25])
  );
  sky130_fd_sc_hd__xor2_2 _104_ (
    .A(\counter[26] ),
    .B(axi_araddr[26]),
    .X(axi_rdata[26])
  );
  sky130_fd_sc_hd__xor2_2 _105_ (
    .A(\counter[27] ),
    .B(axi_araddr[27]),
    .X(axi_rdata[27])
  );
  sky130_fd_sc_hd__xor2_2 _106_ (
    .A(\counter[28] ),
    .B(axi_araddr[28]),
    .X(axi_rdata[28])
  );
  sky130_fd_sc_hd__xor2_2 _107_ (
    .A(\counter[29] ),
    .B(axi_araddr[29]),
    .X(axi_rdata[29])
  );
  sky130_fd_sc_hd__xor2_2 _108_ (
    .A(\counter[30] ),
    .B(axi_araddr[30]),
    .X(axi_rdata[30])
  );
  sky130_fd_sc_hd__xor2_2 _109_ (
    .A(\counter[31] ),
    .B(axi_araddr[31]),
    .X(axi_rdata[31])
  );
  sky130_fd_sc_hd__nand2_2 _110_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .Y(_033_)
  );
  sky130_fd_sc_hd__or2_2 _111_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__and2_2 _112_ (
    .A(_033_),
    .B(_034_),
    .X(_011_)
  );
  sky130_fd_sc_hd__xnor2_2 _113_ (
    .A(\counter[2] ),
    .B(_033_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__and4_2 _114_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .C(\counter[2] ),
    .D(\counter[3] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__a31o_2 _115_ (
    .A1(\counter[0] ),
    .A2(\counter[1] ),
    .A3(\counter[2] ),
    .B1(\counter[3] ),
    .X(_036_)
  );
  sky130_fd_sc_hd__and2b_2 _116_ (
    .A_N(_035_),
    .B(_036_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand2_2 _117_ (
    .A(\counter[4] ),
    .B(_035_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xor2_2 _118_ (
    .A(\counter[4] ),
    .B(_035_),
    .X(_026_)
  );
  sky130_fd_sc_hd__xnor2_2 _119_ (
    .A(\counter[5] ),
    .B(_037_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__and4_2 _120_ (
    .A(\counter[4] ),
    .B(\counter[5] ),
    .C(\counter[6] ),
    .D(_035_),
    .X(_038_)
  );
  sky130_fd_sc_hd__a31o_2 _121_ (
    .A1(\counter[4] ),
    .A2(\counter[5] ),
    .A3(_035_),
    .B1(\counter[6] ),
    .X(_039_)
  );
  sky130_fd_sc_hd__and2b_2 _122_ (
    .A_N(_038_),
    .B(_039_),
    .X(_028_)
  );
  sky130_fd_sc_hd__and4_2 _123_ (
    .A(\counter[4] ),
    .B(\counter[5] ),
    .C(\counter[6] ),
    .D(\counter[7] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand2_2 _124_ (
    .A(_035_),
    .B(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21a_2 _125_ (
    .A1(\counter[7] ),
    .A2(_038_),
    .B1(_041_),
    .X(_029_)
  );
  sky130_fd_sc_hd__xnor2_2 _126_ (
    .A(\counter[8] ),
    .B(_041_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__and2_2 _127_ (
    .A(\counter[8] ),
    .B(\counter[9] ),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand2_2 _128_ (
    .A(\counter[8] ),
    .B(\counter[9] ),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a31o_2 _129_ (
    .A1(\counter[8] ),
    .A2(_035_),
    .A3(_040_),
    .B1(\counter[9] ),
    .X(_044_)
  );
  sky130_fd_sc_hd__o21a_2 _130_ (
    .A1(_041_),
    .A2(_043_),
    .B1(_044_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and4_2 _131_ (
    .A(\counter[10] ),
    .B(_035_),
    .C(_040_),
    .D(_042_),
    .X(_045_)
  );
  sky130_fd_sc_hd__o21ba_2 _132_ (
    .A1(_041_),
    .A2(_043_),
    .B1_N(\counter[10] ),
    .X(_046_)
  );
  sky130_fd_sc_hd__nor2_2 _133_ (
    .A(_045_),
    .B(_046_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__and2_2 _134_ (
    .A(\counter[11] ),
    .B(_045_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor2_2 _135_ (
    .A(\counter[11] ),
    .B(_045_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_2 _136_ (
    .A(_047_),
    .B(_048_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xor2_2 _137_ (
    .A(\counter[12] ),
    .B(_047_),
    .X(_003_)
  );
  sky130_fd_sc_hd__a21oi_2 _138_ (
    .A1(\counter[12] ),
    .A2(_047_),
    .B1(\counter[13] ),
    .Y(_049_)
  );
  sky130_fd_sc_hd__and3_2 _139_ (
    .A(\counter[12] ),
    .B(\counter[13] ),
    .C(_047_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor2_2 _140_ (
    .A(_049_),
    .B(_050_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and4_2 _141_ (
    .A(\counter[12] ),
    .B(\counter[13] ),
    .C(\counter[14] ),
    .D(_047_),
    .X(_051_)
  );
  sky130_fd_sc_hd__xor2_2 _142_ (
    .A(\counter[14] ),
    .B(_050_),
    .X(_005_)
  );
  sky130_fd_sc_hd__and4_2 _143_ (
    .A(\counter[12] ),
    .B(\counter[13] ),
    .C(\counter[14] ),
    .D(\counter[15] ),
    .X(_052_)
  );
  sky130_fd_sc_hd__and3_2 _144_ (
    .A(\counter[11] ),
    .B(_045_),
    .C(_052_),
    .X(_053_)
  );
  sky130_fd_sc_hd__o21ba_2 _145_ (
    .A1(\counter[15] ),
    .A2(_051_),
    .B1_N(_053_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nand2_2 _146_ (
    .A(\counter[16] ),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__xor2_2 _147_ (
    .A(\counter[16] ),
    .B(_053_),
    .X(_007_)
  );
  sky130_fd_sc_hd__xnor2_2 _148_ (
    .A(\counter[17] ),
    .B(_054_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a31oi_2 _149_ (
    .A1(\counter[16] ),
    .A2(\counter[17] ),
    .A3(_053_),
    .B1(\counter[18] ),
    .Y(_055_)
  );
  sky130_fd_sc_hd__and4_2 _150_ (
    .A(\counter[16] ),
    .B(\counter[17] ),
    .C(\counter[18] ),
    .D(_053_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nor2_2 _151_ (
    .A(_055_),
    .B(_056_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__and4_2 _152_ (
    .A(\counter[16] ),
    .B(\counter[17] ),
    .C(\counter[18] ),
    .D(\counter[19] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__and4_2 _153_ (
    .A(\counter[11] ),
    .B(_045_),
    .C(_052_),
    .D(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__o21ba_2 _154_ (
    .A1(\counter[19] ),
    .A2(_056_),
    .B1_N(_058_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xor2_2 _155_ (
    .A(\counter[20] ),
    .B(_058_),
    .X(_012_)
  );
  sky130_fd_sc_hd__a21oi_2 _156_ (
    .A1(\counter[20] ),
    .A2(_058_),
    .B1(\counter[21] ),
    .Y(_059_)
  );
  sky130_fd_sc_hd__and2_2 _157_ (
    .A(\counter[20] ),
    .B(\counter[21] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__a21oi_2 _158_ (
    .A1(_058_),
    .A2(_060_),
    .B1(_059_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a21oi_2 _159_ (
    .A1(_058_),
    .A2(_060_),
    .B1(\counter[22] ),
    .Y(_061_)
  );
  sky130_fd_sc_hd__and3_2 _160_ (
    .A(\counter[22] ),
    .B(_058_),
    .C(_060_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor2_2 _161_ (
    .A(_061_),
    .B(_062_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and3_2 _162_ (
    .A(\counter[21] ),
    .B(\counter[22] ),
    .C(\counter[23] ),
    .X(_063_)
  );
  sky130_fd_sc_hd__and3_2 _163_ (
    .A(\counter[20] ),
    .B(_057_),
    .C(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__and4_2 _164_ (
    .A(\counter[11] ),
    .B(_045_),
    .C(_052_),
    .D(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__and4_2 _165_ (
    .A(\counter[22] ),
    .B(\counter[23] ),
    .C(_057_),
    .D(_060_),
    .X(_066_)
  );
  sky130_fd_sc_hd__and4_2 _166_ (
    .A(\counter[11] ),
    .B(_045_),
    .C(_052_),
    .D(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__o21ba_2 _167_ (
    .A1(\counter[23] ),
    .A2(_062_),
    .B1_N(_065_),
    .X(_015_)
  );
  sky130_fd_sc_hd__xor2_2 _168_ (
    .A(\counter[24] ),
    .B(_065_),
    .X(_016_)
  );
  sky130_fd_sc_hd__a21oi_2 _169_ (
    .A1(\counter[24] ),
    .A2(_065_),
    .B1(\counter[25] ),
    .Y(_068_)
  );
  sky130_fd_sc_hd__and3_2 _170_ (
    .A(\counter[24] ),
    .B(\counter[25] ),
    .C(_065_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nor2_2 _171_ (
    .A(_068_),
    .B(_069_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__and4_2 _172_ (
    .A(\counter[24] ),
    .B(\counter[25] ),
    .C(\counter[26] ),
    .D(_067_),
    .X(_070_)
  );
  sky130_fd_sc_hd__o21ba_2 _173_ (
    .A1(\counter[26] ),
    .A2(_069_),
    .B1_N(_070_),
    .X(_018_)
  );
  sky130_fd_sc_hd__and4_2 _174_ (
    .A(\counter[24] ),
    .B(\counter[25] ),
    .C(\counter[26] ),
    .D(\counter[27] ),
    .X(_071_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _175_ (
    .A1_N(_065_),
    .A2_N(_071_),
    .B1(_070_),
    .B2(\counter[27] ),
    .X(_019_)
  );
  sky130_fd_sc_hd__a21oi_2 _176_ (
    .A1(_065_),
    .A2(_071_),
    .B1(\counter[28] ),
    .Y(_072_)
  );
  sky130_fd_sc_hd__and3_2 _177_ (
    .A(\counter[28] ),
    .B(_067_),
    .C(_071_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor2_2 _178_ (
    .A(_072_),
    .B(_073_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__and2_2 _179_ (
    .A(\counter[28] ),
    .B(\counter[29] ),
    .X(_074_)
  );
  sky130_fd_sc_hd__and3_2 _180_ (
    .A(_067_),
    .B(_071_),
    .C(_074_),
    .X(_075_)
  );
  sky130_fd_sc_hd__o21ba_2 _181_ (
    .A1(\counter[29] ),
    .A2(_073_),
    .B1_N(_075_),
    .X(_021_)
  );
  sky130_fd_sc_hd__and4_2 _182_ (
    .A(\counter[30] ),
    .B(_065_),
    .C(_071_),
    .D(_074_),
    .X(_076_)
  );
  sky130_fd_sc_hd__xor2_2 _183_ (
    .A(\counter[30] ),
    .B(_075_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xor2_2 _184_ (
    .A(\counter[31] ),
    .B(_076_),
    .X(_024_)
  );
  sky130_fd_sc_hd__xor2_2 _185_ (
    .A(uart_tx),
    .B(uart_rx),
    .X(_032_)
  );
  sky130_fd_sc_hd__dfrtp_2 _186_ (
    .CLK(clk),
    .D(_032_),
    .Q(uart_tx),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _187_ (
    .CLK(clk),
    .D(_000_),
    .Q(\counter[0] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _188_ (
    .CLK(clk),
    .D(_011_),
    .Q(\counter[1] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _189_ (
    .CLK(clk),
    .D(_022_),
    .Q(\counter[2] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _190_ (
    .CLK(clk),
    .D(_025_),
    .Q(\counter[3] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _191_ (
    .CLK(clk),
    .D(_026_),
    .Q(\counter[4] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _192_ (
    .CLK(clk),
    .D(_027_),
    .Q(\counter[5] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _193_ (
    .CLK(clk),
    .D(_028_),
    .Q(\counter[6] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _194_ (
    .CLK(clk),
    .D(_029_),
    .Q(\counter[7] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _195_ (
    .CLK(clk),
    .D(_030_),
    .Q(\counter[8] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _196_ (
    .CLK(clk),
    .D(_031_),
    .Q(\counter[9] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _197_ (
    .CLK(clk),
    .D(_001_),
    .Q(\counter[10] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _198_ (
    .CLK(clk),
    .D(_002_),
    .Q(\counter[11] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _199_ (
    .CLK(clk),
    .D(_003_),
    .Q(\counter[12] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _200_ (
    .CLK(clk),
    .D(_004_),
    .Q(\counter[13] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _201_ (
    .CLK(clk),
    .D(_005_),
    .Q(\counter[14] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _202_ (
    .CLK(clk),
    .D(_006_),
    .Q(\counter[15] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _203_ (
    .CLK(clk),
    .D(_007_),
    .Q(\counter[16] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _204_ (
    .CLK(clk),
    .D(_008_),
    .Q(\counter[17] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _205_ (
    .CLK(clk),
    .D(_009_),
    .Q(\counter[18] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _206_ (
    .CLK(clk),
    .D(_010_),
    .Q(\counter[19] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _207_ (
    .CLK(clk),
    .D(_012_),
    .Q(\counter[20] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _208_ (
    .CLK(clk),
    .D(_013_),
    .Q(\counter[21] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _209_ (
    .CLK(clk),
    .D(_014_),
    .Q(\counter[22] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _210_ (
    .CLK(clk),
    .D(_015_),
    .Q(\counter[23] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _211_ (
    .CLK(clk),
    .D(_016_),
    .Q(\counter[24] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _212_ (
    .CLK(clk),
    .D(_017_),
    .Q(\counter[25] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _213_ (
    .CLK(clk),
    .D(_018_),
    .Q(\counter[26] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _214_ (
    .CLK(clk),
    .D(_019_),
    .Q(\counter[27] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _215_ (
    .CLK(clk),
    .D(_020_),
    .Q(\counter[28] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _216_ (
    .CLK(clk),
    .D(_021_),
    .Q(\counter[29] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _217_ (
    .CLK(clk),
    .D(_023_),
    .Q(\counter[30] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _218_ (
    .CLK(clk),
    .D(_024_),
    .Q(\counter[31] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _219_ (
    .CLK(clk),
    .D(\counter[8] ),
    .Q(gpio_out[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _220_ (
    .CLK(clk),
    .D(\counter[9] ),
    .Q(gpio_out[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _221_ (
    .CLK(clk),
    .D(\counter[10] ),
    .Q(gpio_out[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _222_ (
    .CLK(clk),
    .D(\counter[11] ),
    .Q(gpio_out[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _223_ (
    .CLK(clk),
    .D(\counter[12] ),
    .Q(gpio_out[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _224_ (
    .CLK(clk),
    .D(\counter[13] ),
    .Q(gpio_out[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _225_ (
    .CLK(clk),
    .D(\counter[14] ),
    .Q(gpio_out[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _226_ (
    .CLK(clk),
    .D(\counter[15] ),
    .Q(gpio_out[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__conb_1 _227_ (
    .HI(axi_bvalid)
  );
  sky130_fd_sc_hd__conb_1 _228_ (
    .HI(axi_rvalid)
  );
  sky130_fd_sc_hd__conb_1 _229_ (
    .LO(axi_bresp[1])
  );
  sky130_fd_sc_hd__conb_1 _230_ (
    .LO(axi_rresp[0])
  );
  sky130_fd_sc_hd__conb_1 _231_ (
    .LO(axi_rresp[1])
  );
  sky130_fd_sc_hd__conb_1 _232_ (
    .LO(axi_bresp[0])
  );
  sky130_fd_sc_hd__buf_2 _233_ (
    .A(axi_arvalid),
    .X(axi_arready)
  );
  sky130_fd_sc_hd__buf_2 _234_ (
    .A(axi_awvalid),
    .X(axi_awready)
  );
  sky130_fd_sc_hd__buf_2 _235_ (
    .A(axi_wvalid),
    .X(axi_wready)
  );
endmodule
