// Auto-generated by LibreLane
module riscv_soc_top(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input rst_n,
  input uart_rx,
  output uart_tx,
  input[7:0] gpio_in,
  output[7:0] gpio_out,
  input[31:0] axi_awaddr,
  input axi_awvalid,
  output axi_awready,
  input[31:0] axi_wdata,
  input[3:0] axi_wstrb,
  input axi_wvalid,
  output axi_wready,
  output[1:0] axi_bresp,
  output axi_bvalid,
  input axi_bready,
  input[31:0] axi_araddr,
  input axi_arvalid,
  output axi_arready,
  output[31:0] axi_rdata,
  output[1:0] axi_rresp,
  output axi_rvalid,
  input axi_rready,
  input ext_interrupt
);
endmodule
